---
# Oracle jdk
- name: Copy jdk.tar.gz to remote host 
  copy:
    src: ../files/jdk-{{ jdk_version }}-linux-x64.tar.gz
    dest: /home/install/jdk-{{ jdk_version }}-linux-x64.tar.gz
    force: no

- name: Deploy jdk environment
  shell: cd /opt && rm -rf jdk;mkdir jdk && tar -xf /home/install/jdk-{{ jdk_version }}-linux-x64.tar.gz -C jdk --strip-components 1

- name: Add system environemt variables
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - export JAVA_HOME=/opt/jdk
    - export PATH=$PATH:$JAVA_HOME/bin
- name: Source /etc/profile
  shell: source /etc/profile
