---
- name: Add haproxy systemd unit
  template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
    force: yes

- name: Reload systemd unit
  systemd:
    daemon_reload: yes
