---
- name: Set ip forwarding
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: net.ipv4.ip_forward
    value: "1"
    state: present
- name: Forbidden swap
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: vm.swappiness
    value: "0"
    state: present
    reload: yes
