- name: Create elastic systemd unit
  template:
    src: elasticseach.service.j2
    dest: /etc/systemd/system/elasticsearch.service
    force: yes
- name: Reload systemd unit
  systemd:
    daemon_reload: yes
