---
- name: Create nginx group
  group:
    name: nginx
    state: present
- name: Create nginx user
  user:
    name: nginx
    shell: /sbin/nologin
    state: present
    create_home: no

- name: Install depend on sys packages
  yum:
    name:
      - gcc
      - openssl-devel
      - zlib-devel
      - pcre-devel
    state: present

- name: Copy package to remote host
  copy: 
    src: ../files/tengine-{{ tengine_version }}.tar.gz 
    dest: /usr/local/tengine-{{ tengine_version }}.tar.gz
    force: no

- name: Install nginx
  shell: cd /usr/local/ && tar -xf tengine-{{ tengine_version }}.tar.gz && cd tengine-{{ tengine_version }} && ./configure --with-http_gzip_static_module --with-http_v2_module --with-http_realip_module --with-http_flv_module && make && make install

- name: Config nginx appliction
  template:
    src: nginx.conf.j2
    dest: /usr/local/nginx/conf/nginx.conf
    force: yes
- name: Create config templates of nginx
  file:
    path: /usr/local/nginx/conf/vhost/example_com
    state: directory
    recurse: yes
- name: Create config templates of nginx
  template:
    src: example.com.conf.j2
    dest: /usr/local/nginx/conf/vhost/example_com/example.com.conf
    force: no
  notify: Reload nginx

- name: Test nginx config file
  command: /usr/local/nginx/sbin/nginx -t
  register: command_result
  failed_when: "'FAILED' in command_result"

- name: Change file owner
  file:
    path: /usr/local/nginx
    owner: nginx
    group: nginx
    recurse: yes
    state: directory

- name: Start nginx...
  systemd:
    name: nginx
    state: started
    enabled: no
