---
- name: Nginx logs manage
  template: 
    src: logs_nginx.conf.j2
    dest: /usr/local/nginx/conf/logs_nginx.conf
    force: no
- name: Crontab nginx logs
  cron:
    name: Config crontab
    job: "/usr/sbin/logrotate -f /usr/local/nginx/conf/nginx_logs.conf > /dev/null 2>&1"
    minute: "55"
    hour: "23"
