---
- name: Initialization System
  hosts: all1
  remote_user: root

  roles:
    #- init-system

- name: Install MySQL
  hosts: dbserver1
  remote_user: root

  roles:
    #- mysql

- name: Install Nginx
  hosts: web
  remote_user: root

  roles:
    - tengine
