---
- name: Initialization System
  hosts: owner
  remote_user: root

  roles:
    - init-system

- name: Install MySQL
  hosts: dbserver
  remote_user: root

  roles:
    - mysql

- name: Install Nginx
  hosts: web
  remote_user: root

  roles:
    - tengine
