---
- name: Install zabbix-agent
  hosts: zabbix
  remote_user: root
  vars:
    host_ip: "{{ansible_default_ipv4['address']}}"

  roles:
    - zabbix-agent

- name: Install keepalived (master||backup)
  hosts: keepalived
  remote_user: root
  # serial: 1

  roles:
    - keepalived
    - dnsmasq

- name: Install MySQL
  hosts: dbserver
  remote_user: root
  
  roles:
    - mysql
