---
- name: Create zabbix-agent systemd unit
  template:
    src: zabbix-agent.service.j2
    dest: /etc/systemd/system/zabbix-agent.service
    force: no
- name: Reload systemd unit
  systemd:
    daemon_reload: yes
